# FROM node:lts-alpine 
# WORKDIR /app
# COPY package*.json ./
# RUN npm install
# COPY ./ .

# ENV NODE_ENV=production

# RUN npm run build


FROM node:latest

WORKDIR /app

EXPOSE 3000

RUN yarn install