version: "3"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: backend
    container_name: backend
    volumes:
      - ".:/backend/app"
    networks:
      flask-vue-network:
        aliases:
          - flask-api

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: frontend
    container_name: frontend
    hostname: frontend
    volumes:
      - "./client:/frontend/app"
      - "./client/node_modules:/frontend/app/node_modules"
    command: "yarn build"

    networks:
      flask-vue-network:
        aliases:
          - frontend

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    depends_on:
      - backend
      - frontend
    links:
      - frontend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./client/dist:/usr/share/nginx/html
    ports:
      - 80:80
      - 443:443
    networks:
      - flask-vue-network
networks:
  flask-vue-network:
