version: "3"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: backend
    container_name: backend
    volumes:
      - "./backend:/app"
    command: "pipenv run gunicorn -c gunicorn_config.py wsgi:app"

    networks:
      flask-vue-network:
        aliases:
          - flask-api

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: frontend
    container_name: frontend
    hostname: frontend
    volumes:
      - "./frontend:/app"
      - "./frontend/node_modules:/app/node_modules"
    command: "yarn build"

    networks:
      flask-vue-network:
        aliases:
          - frontend

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: nginx
    container_name: nginx
    depends_on:
      - backend
      - frontend
    links:
      - frontend
    volumes:
      - ./frontend/dist:/usr/share/nginx/html
    ports:
      - 80:80
      - 443:443
    networks:
      - flask-vue-network
networks:
  flask-vue-network:
